name = "MiniPkg"
uuid = "8954e995-77c7-47e7-865d-74c5dce3e9c2"
authors = ["Jo1931 <johanneslpld@googlemail.com.de>"]
version = "0.2.0"

[deps]
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
StatsBase = "0.34.10"
